// Mock data for development
import type { Article, Match, Team, Player, Category, Poll } from '@/types';

export const mockArticles: Article[] = [
  {
    id: '1',
    title: 'Morocco Stuns Spain in World Cup Qualifier',
    slug: 'morocco-stuns-spain-in-world-cup-qualifier',
    content: 'Morocco delivered a stunning performance against Spain in the World Cup qualifier match, winning 2-0 with goals from Ziyech and En-Nesyri.',
    excerpt: 'Morocco delivered a stunning performance against Spain in the World Cup qualifier match.',
    featuredImage: '/images/mock/morocco-spain.jpg',
    author: 'Ahmed Benali',
    publishDate: '2025-03-24T10:00:00Z',
    categories: ['World Cup', 'Morocco', 'International'],
    tags: ['Morocco', 'Spain', 'World Cup Qualifier'],
    isFeatured: true,
    viewCount: 1250,
  },
  {
    id: '2',
    title: 'Transfer Rumors: Top Premier League Targets for Summer',
    slug: 'transfer-rumors-top-premier-league-targets-for-summer',
    content: 'As the summer transfer window approaches, Premier League clubs are eyeing several top talents across Europe. Manchester United is reportedly interested in Moroccan defender Achraf Hakimi.',
    excerpt: 'Premier League clubs are eyeing several top talents across Europe for the summer transfer window.',
    featuredImage: '/images/mock/transfers.jpg',
    author: 'Sarah Johnson',
    publishDate: '2025-03-23T14:30:00Z',
    categories: ['Transfers', 'Premier League'],
    tags: ['Transfers', 'Premier League', 'Hakimi'],
    isFeatured: false,
    viewCount: 980,
  },
  {
    id: '3',
    title: 'Tactical Analysis: How Morocco\'s Defense Shut Down Spain',
    slug: 'tactical-analysis-how-moroccos-defense-shut-down-spain',
    content: 'A deep dive into the tactical masterclass by Morocco\'s coach, utilizing a compact 4-3-3 formation that neutralized Spain\'s tiki-taka style.',
    excerpt: 'A deep dive into the tactical masterclass by Morocco\'s coach against Spain.',
    featuredImage: '/images/mock/tactics.jpg',
    author: 'Carlos Mendez',
    publishDate: '2025-03-22T09:15:00Z',
    categories: ['Tactical Analysis', 'Morocco', 'International'],
    tags: ['Tactics', 'Morocco', 'Spain'],
    isFeatured: true,
    viewCount: 1560,
  },
  {
    id: '4',
    title: 'Rising Star: Moroccan Midfielder Making Waves in Bundesliga',
    slug: 'rising-star-moroccan-midfielder-making-waves-in-bundesliga',
    content: 'Young Moroccan midfielder Amine Harit is turning heads with his performances for Schalke 04 in the Bundesliga this season.',
    excerpt: 'Young Moroccan midfielder Amine Harit is turning heads in the Bundesliga.',
    featuredImage: '/images/mock/harit.jpg',
    author: 'Thomas Mueller',
    publishDate: '2025-03-21T16:45:00Z',
    categories: ['Player Spotlight', 'Bundesliga', 'Morocco'],
    tags: ['Amine Harit', 'Schalke 04', 'Bundesliga'],
    isFeatured: false,
    viewCount: 720,
  },
  {
    id: '5',
    title: 'Champions League Draw: Moroccan Stars Set to Shine',
    slug: 'champions-league-draw-moroccan-stars-set-to-shine',
    content: 'With the Champions League quarterfinal draw complete, several Moroccan players will be facing off against each other in key matches.',
    excerpt: 'Several Moroccan players will be facing off against each other in Champions League quarterfinals.',
    featuredImage: '/images/mock/champions-league.jpg',
    author: 'Ahmed Benali',
    publishDate: '2025-03-20T11:30:00Z',
    categories: ['Champions League', 'Morocco'],
    tags: ['Champions League', 'Ziyech', 'Hakimi'],
    isFeatured: true,
    viewCount: 1820,
  },
];

export const mockTeams: Team[] = [
  {
    id: '1',
    name: 'Morocco National Team',
    shortName: 'Morocco',
    logo: '/images/mock/teams/morocco.png',
    country: 'Morocco',
    founded: 1955,
    stadium: 'Stade Mohammed V',
  },
  {
    id: '2',
    name: 'Spain National Team',
    shortName: 'Spain',
    logo: '/images/mock/teams/spain.png',
    country: 'Spain',
    founded: 1920,
    stadium: 'Santiago Bernabéu',
  },
  {
    id: '3',
    name: 'Raja Casablanca',
    shortName: 'Raja',
    logo: '/images/mock/teams/raja.png',
    country: 'Morocco',
    founded: 1949,
    stadium: 'Stade Mohammed V',
  },
  {
    id: '4',
    name: 'Wydad Casablanca',
    shortName: 'Wydad',
    logo: '/images/mock/teams/wydad.png',
    country: 'Morocco',
    founded: 1937,
    stadium: 'Stade Mohammed V',
  },
];

export const mockMatches: Match[] = [
  {
    id: '1',
    homeTeam: mockTeams[0],
    awayTeam: mockTeams[1],
    homeScore: 2,
    awayScore: 0,
    date: '2025-03-24',
    time: '20:00',
    venue: 'Stade Mohammed V',
    competition: 'World Cup Qualifier',
    status: 'completed',
    matchWeek: 3,
    highlights: 'https://example.com/highlights/morocco-spain',
  },
  {
    id: '2',
    homeTeam: mockTeams[2],
    awayTeam: mockTeams[3],
    date: '2025-03-28',
    time: '18:30',
    venue: 'Stade Mohammed V',
    competition: 'Botola Pro',
    status: 'scheduled',
    matchWeek: 25,
  },
  {
    id: '3',
    homeTeam: mockTeams[3],
    awayTeam: mockTeams[2],
    homeScore: 1,
    awayScore: 1,
    date: '2025-03-15',
    time: '18:30',
    venue: 'Stade Mohammed V',
    competition: 'Botola Pro',
    status: 'completed',
    matchWeek: 24,
    highlights: 'https://example.com/highlights/wydad-raja',
  },
];

export const mockPlayers: Player[] = [
  {
    id: '1',
    name: 'Hakim Ziyech',
    position: 'Midfielder',
    nationality: 'Morocco',
    dateOfBirth: '1993-03-19',
    teamId: '1',
    image: '/images/mock/players/ziyech.jpg',
    jerseyNumber: 10,
  },
  {
    id: '2',
    name: 'Achraf Hakimi',
    position: 'Defender',
    nationality: 'Morocco',
    dateOfBirth: '1998-11-04',
    teamId: '1',
    image: '/images/mock/players/hakimi.jpg',
    jerseyNumber: 2,
  },
  {
    id: '3',
    name: 'Yassine Bounou',
    position: 'Goalkeeper',
    nationality: 'Morocco',
    dateOfBirth: '1991-04-05',
    teamId: '1',
    image: '/images/mock/players/bounou.jpg',
    jerseyNumber: 1,
  },
];

export const mockCategories: Category[] = [
  {
    id: '1',
    name: 'Morocco',
    slug: 'morocco',
    description: 'News and updates about Moroccan football',
  },
  {
    id: '2',
    name: 'International',
    slug: 'international',
    description: 'International football news and matches',
  },
  {
    id: '3',
    name: 'Transfers',
    slug: 'transfers',
    description: 'Transfer news, rumors, and updates',
  },
  {
    id: '4',
    name: 'Tactical Analysis',
    slug: 'tactical-analysis',
    description: 'In-depth tactical analysis of matches and teams',
  },
  {
    id: '5',
    name: 'Botola Pro',
    slug: 'botola-pro',
    description: 'News and updates about the Moroccan Botola Pro league',
  },
];

export const mockPolls: Poll[] = [
  {
    id: '1',
    question: 'Who will win the Botola Pro this season?',
    options: [
      { id: '1', text: 'Raja Casablanca', votes: 245 },
      { id: '2', text: 'Wydad Casablanca', votes: 231 },
      { id: '3', text: 'AS FAR', votes: 112 },
      { id: '4', text: 'RS Berkane', votes: 87 },
    ],
    startDate: '2025-03-15T00:00:00Z',
    endDate: '2025-04-15T00:00:00Z',
    isActive: true,
  },
  {
    id: '2',
    question: 'Who is Morocco\'s best player currently?',
    options: [
      { id: '1', text: 'Hakim Ziyech', votes: 356 },
      { id: '2', text: 'Achraf Hakimi', votes: 298 },
      { id: '3', text: 'Yassine Bounou', votes: 187 },
      { id: '4', text: 'Sofyan Amrabat', votes: 145 },
    ],
    startDate: '2025-03-10T00:00:00Z',
    endDate: '2025-03-25T00:00:00Z',
    isActive: true,
  },
];
